### ISSUE TITLE
AutoValue not calculating on fields with validation

### ISSUE THREAD

**Issue by dcs619** [aldeed/meteor-simple-schema#150]
I have a geocode schema that returns an auto-value array from the coordinates, but the inner values are always null.  Is there a delay calculation that should be set on autoValue?

The schema I'm using (in coffeescript)

```
GeometrySchema = new SimpleSchema(
  lng:
    type: Number
    decimal: true
    min: -180
    max: 180
    optional: true
  lat:
    type: Number
    decimal: true
    min: -90
    max: 90
    optional: true
  coordinates:
    type: [Number]
    decimal: true
    autoValue: ->
      return [this.lng, this.lat]
)

geocodes = new Meteor.Collection("geocodes", { schema: GeometrySchema })
geocodes.insert({
    lat: 34.597775
    lng: -82.622364
})
```
