### ISSUE TITLE
Empty string error on optional field

### ISSUE THREAD

**Issue by dcs619** [aldeed/meteor-simple-schema#156]
I think this is related to #64, but I can't get an object to save with an optional empty string.  I get error: zip is required.

```
zip:
    type: String
    regEx: /^\d{5}(-\d{4})?$/
    optional: true
```

This works if I replace empty strings with _undefined_ before I try the insert.  However, I'd like to keep my data set as a valid JSON string.  Any suggestions?
