### ISSUE TITLE
Cannot use 'in' operator to search for '$pushAll'

### ISSUE THREAD

**Issue by ndemoreau** [aldeed/meteor-simple-schema#189]
I have this schema:

```
Schemas.Project = new SimpleSchema
  name:
    type: String
    label: "Name"
    max: 50

  description:
    type: String
    label: "Description"
    max: 350

  published:
    type: Boolean
    optional: true

  "pictures.$.id":
    type: String
```

And I try to update it this way after uploading an image:

```
Images.insert file, (err, fileObj) ->
    current_project = Router.current().params._id
    picture_id= fileObj._id
    Projects.update
      "_id": current_project
      $push: {
        "pictures": {"id": picture_id}
      }
```

But I get this error statement:

Exception in delivering result of invoking '/cfs.images.filerecord/insert': TypeError: Cannot use 'in' operator to search for '$pushAll' in undefined
    at SimpleSchema.clean (http://localhost:3000/packages/aldeed_simple-schema.js?f9f115ce8032ac525bc2dde8cca4ab5937f22441:2121:21)
    at doClean (http://localhost:3000/packages/aldeed_collection2.js?525ba7d2b38809f4b3de1e552fabb647d8fc56ae:274:12)
    at doValidate (http://localhost:3000/packages/aldeed_collection2.js?525ba7d2b38809f4b3de1e552fabb647d8fc56ae:300:3)
    at _.each.Mongo.Collection.(anonymous function) [as update](http://localhost:3000/packages/aldeed_collection2.js?525ba7d2b38809f4b3de1e552fabb647d8fc56ae:178:25)
    at http://localhost:3000/client/views/files/upload_form.coffee.js?57797942b21d0bd1f29738e51d598592d6455db7:14:20
    at http://localhost:3000/packages/cfs_collection.js?5245550dee5967dd02d077d812cf86557ee2ce95:274:9
    at _.each.Mongo.Collection.(anonymous function).wrappedCallback (http://localhost:3000/packages/mongo.js?9bc2c5a8b2796fab86b51660ca643e5a49a30c84:618:9)
    at Meteor.bindEnvironment [as _callback](http://localhost:3000/packages/meteor.js?61916b1060b33931a21f104fbffb67c2f3d493c5:973:22)
    at _.extend._maybeInvokeCallback (http://localhost:3000/packages/ddp.js?1f971b2ac9f4bdab7372cb5098ed1e26ff98dfb2:3853:12)
    at _.extend.dataVisible (http://localhost:3000/packages/ddp.js?1f971b2ac9f4bdab7372cb5098ed1e26ff98dfb2:3882:10)

When I run the exact same updat -> push command, at the same time in console, it works.

Any idea what it can be?

Thanks.
