### ISSUE TITLE
this.field(name).value returns undefined in 2.3.3

### ISSUE THREAD

**Issue by satyavh** [aldeed/meteor-simple-schema#340]
Just upgraded to 2.3.3 and noticed that custom validation is suddenly not working anymore. Seems that this.field(name).value in custom validation always returns undefined. Here's my code

```
    new SimpleSchema(
      currentPassword:
        type: String
        min: 4
        instructions: 'Current password'
        label: 'Current password'
      newPassword:
        type: String
        min: 4
        label: 'New password'        
      confirmPassword:
        type: String
        min: 4
        label: 'Confirm new password'   
        custom: ->
          if @value != @field('newPassword').value 
            return "passwordMismatch"
```

@field('newPassword').value returns undefined. Before latest verion this was working just fine
