### ISSUE TITLE
Blackbox being ignored

### ISSUE THREAD

**Issue by lingz** [aldeed/meteor-simple-schema#95]
I have a strange error, where I'm trying to update into a blackboxed, object but it seems like the blackbox option is being ignored.

Here are the logs:

```
    SimpleSchema.clean: filtered out value that would have affected key "communities.$b8f414b244e1d2767624b88", which is not allowed by the schema
    SimpleSchema.clean: filtered out value that would have affected key "communities.$b8f414b244e1d2767624b88.$", which is not allowed by the schema
```

While in the schema it says:

```
  communities:
    type: Object
    blackbox: true
    optional: true
    autoValue: () ->
      if (!@isSet && !(@isUpdate || @isUpsert))
        return {}
```

Any ideas on how to debug further?
